create table Product (id bigint generated by default as identity, description varchar(255), price double, productName varchar(255), primary key (id))
create table User (id bigint generated by default as identity, LastName varchar(255), email varchar(255), firstName varchar(255), password varchar(255), primary key (id))
